<div id="wrapper">

	<form name="register-form" class="login-form" action="register.php" method="post">
	
		<div class="header">
		<h1>Registeration Form</h1>
		<span>Please Enter the details</span>
		</div>
	
		<div class="content">
		<input name="username" type="text" class="input username" placeholder="Username" />
		<div class="user-icon"></div>
		<input name="password" type="password" class="input password" placeholder="Password" />
		<div class="pass-icon"></div>	
		<input name="email" type="text" class="input username" placeholder="Email-Id" />
		</div>

		<div class="footer">
		<input type="submit" name="submit" value="Register" class="register" />
		</div>
	
	</form>

</div>
<div class="gradient"></div>